name: Auto Upload Contents

on:
  workflow_dispatch:
    inputs:
      n_content:
        description: "Number of posts to generate and upload"
        required: true
        default: "1"
      topic:
        description: "Topic for content generation"
        required: true
        default: "Free Topic"
      enable_langchain_tracing:
        description: "Enable LangChain tracing (true/false)"
        required: false
        default: "false"

jobs:
  generate-content:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v3
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root

      - name: Generate content
        run: |
          source $VENV
          export PYTHONPATH=$PYTHONPATH:${{ github.workspace }}
          python scripts/generate_content.py --n-content ${{ github.event.inputs.n_content }} --topic "${{ github.event.inputs.topic }}"
        env:
          VENV: ${{ github.workspace }}/.venv/bin/activate
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          LANGCHAIN_TRACING_V2: ${{ github.event.inputs.enable_langchain_tracing }}
          LANGCHAIN_API_KEY: ${{ secrets.LANGCHAIN_API_KEY }}

      - name: Commit and push if changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff --quiet && git diff --staged --quiet || (git commit -m "📝 Add generated content for ${{ github.event.inputs.topic }}" --no-verify && git push)
